version: 2.1
orbs:
  node: circleci/node@5.0.2
#executors:
#  bxts:
#    docker:
#      - image: cimg/node:15.0.1
#    working_directory: ~/solana-trader-client-ts
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
          name: Install npm
      - run:
          command: sudo npm install -g ts-node
          name: Install ts-node
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: ts-node -v
          name: Check ts-node version to make sure it installed

  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: sudo npm install -g lint
          name: Install ts-node
      - run:
          name: lint
          command: lint

  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: testnet
          command: |
            export AUTH_HEADER=$AUTH_HEADER_TESTNET
            export WALLET_SECRET_KEY=$PRIVATE_KEY
            export WALLET_PUBLIC_KEY=$PUBLIC_KEY
            export API_ENV="testnet"
            export RUN_LIFECYCLE="false"
            echo $AUTH_HEADER
            echo $WALLET_SECRET_KEY
            echo $WALLET_PUBLIC_KEY
            echo $API_ENV
            npm start
      - run:
          name: mainnet
          command: |
            export AUTH_HEADER=$AUTH_HEADER_MAINNET
            export WALLET_SECRET_KEY=$PRIVATE_KEY
            export WALLET_PUBLIC_KEY=$PUBLIC_KEY
            export API_ENV="mainnet"
            export RUN_LIFECYCLE="false"
            echo $AUTH_HEADER
            echo $WALLET_SECRET_KEY
            echo $WALLET_PUBLIC_KEY
            echo $API_ENV
            npm start

workflows:
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          context: trader-api-sdk
          requires:
            - build