version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: sudo npm install -g ts-node
          name: Install ts-node
      - run:
          command: npm ci
          name: Install NPM dependencies for fmt/lint
      - run:
          command: ts-node -v
          name: Check ts-node version to make sure it installed
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  test:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          command: npm run test
          name: run tests

  format:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: format
          command: npm run format

  lint:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: lint
          command: npm run lintCI

workflows:
  build_and_test:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - build
      - lint:
          requires:
            - build
      - format:
          requires:
            - build
      - test:
          requires:
            - build

  nightly:
    when:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - build
      - lint:
          requires:
            - build
      - format:
          requires:
            - build
      - test:
          requires:
            - build
